# Generated by Django 4.0.7 on 2022-09-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_alter_photo_options_alter_photo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelTable(
            name='photo',
            table=None,
        ),
    ]
