# Generated by Django 4.0.7 on 2022-09-28 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image_alter_post_description_alter_post_tags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
        migrations.AlterModelTable(
            name='photo',
            table='blog_photos',
        ),
    ]
