# Generated by Django 4.0.7 on 2022-09-28 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_photo_options_alter_photo_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
