# Generated by Django 4.0.7 on 2022-09-28 16:05

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_remove_video_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_Title', models.CharField(max_length=200)),
                ('tutorial_Body', models.TextField()),
                ('tutorial_Video', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'verbose_name_plural': 'Tutorial',
            },
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
